version: '3'

services: 
    mongo:
        image: mongo:4
        restart: always
        container_name: mongodb
        environment: 
            - MONGO_INITDB_ROOT_USERNAME=${CENTRAL_CUENTAS_MONGO_USER}
            - MONGO_INITDB_ROOT_PASSWORD=${CENTRAL_CUENTAS_MONGO_PASS}
        volumes:
            - mongo_data:/data/db
        ports: 
            - ${CENTRAL_CUENTAS_MONGO_PORT}:${CENTRAL_CUENTAS_MONGO_PORT}
        expose: 
            - ${CENTRAL_CUENTAS_MONGO_PORT}
    
    back:
        container_name: "central-cuentas-service"
        restart: always
        env_file: 
        - .env
        environment: 
            - CENTRAL_CUENTAS_MONGO_COLLECTION=${CENTRAL_CUENTAS_MONGO_COLLECTION}
            - CENTRAL_CUENTAS_MONGO_DB_NAME=${CENTRAL_CUENTAS_MONGO_DB_NAME}
            - CENTRAL_CUENTAS_MONGO_DB_AUTH=${CENTRAL_CUENTAS_MONGO_DB_AUTH}
            - CENTRAL_CUENTAS_MONGO_USER=${CENTRAL_CUENTAS_MONGO_USER}
            - CENTRAL_CUENTAS_MONGO_PASS=${CENTRAL_CUENTAS_MONGO_PASS}
            - CENTRAL_CUENTAS_MONGO_URL=${CENTRAL_CUENTAS_MONGO_URL}
            - CENTRAL_CUENTAS_MONGO_PORT=${CENTRAL_CUENTAS_MONGO_PORT}
        build: 
            context: .
            dockerfile: Dockerfile.build
        ports: 
            - ${CENTRAL_CUENTAS_PORT}:${CENTRAL_CUENTAS_PORT}
        volumes: 
            - .:/usr/src/app
        depends_on: 
            - mongo
        links: 
            - mongo

volumes:
  mongo_data: